---
# How to install Helm 2 (From Script)
#
# This installs the Helm 2 client on all cluster nodes locally

- name: Install Helm 2 using install script
  shell: curl -L https://git.io/get_helm.sh | bash
  args:
    chdir: /root
    creates: /usr/local/bin/helm
  tags:
    - kubernetes-hetzner
    - kubernetes-hetzner-helm2

# Now tiller needs to be installed in the kubernetes cluster
- name: Create tiller SA in kubernetes cluster
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: tiller
        namespace: kube-system
  when: ansible_hostname == kubernetes_hetzner_init_node
  tags:
    - kubernetes-hetzner
    - kubernetes-hetzner-helm2

- name: Create tiller ClusterRoleBinding in kubernetes cluster
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: tiller
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: tiller
          namespace: kube-system
  when: ansible_hostname == kubernetes_hetzner_init_node
  tags:
    - kubernetes-hetzner
    - kubernetes-hetzner-helm2

- name: Initialize Helm 2 and Tiller
  command: |
    helm init --service-account tiller \
    --stable-repo-url=https://kubernetes-charts.storage.googleapis.com \
    --upgrade \
    --automount-service-account-token=true \
    --replicas=1 \
    --history-max=100 \
    --wait
  register: helm_init_result
  changed_when: "'already installed' not in helm_init_result.stdout"
  when: ansible_hostname == kubernetes_hetzner_init_node
  tags:
    - kubernetes-hetzner
    - kubernetes-hetzner-helm2

- name: Get Tiller ClusterIP
  k8s:
    api_version: v1
    kind: Service
    name: tiller-deploy
    namespace: kube-system
  register: kubernetes_hetzner_tiller_service
  when: ansible_hostname == kubernetes_hetzner_init_node
  tags:
    - kubernetes-hetzner
    - kubernetes-hetzner-helm2

- name: Set the Helm 2 host and port
  set_fact:
    kubernetes_hetzner_helm_host: "{{ kubernetes_hetzner_tiller_service.result.spec.clusterIP }}"
    kubernetes_hetzner_helm_port: "{{ kubernetes_hetzner_tiller_service.result.spec.ports[0].port }}"
  when: ansible_hostname == kubernetes_hetzner_init_node
  tags:
    - kubernetes-hetzner
    - kubernetes-hetzner-helm2

- name: Wait for Tiller to become responsive
  wait_for:
    host: '{{ kubernetes_hetzner_helm_host }}'
    port: '{{ kubernetes_hetzner_helm_port }}'
    state: started
  when: ansible_hostname == kubernetes_hetzner_init_node
  tags:
    - kubernetes-hetzner
    - kubernetes-hetzner-helm2
