---
- name: Ensure python3-pip and python3-setuptools are installed for k8s module
  package:
    name: [ python3-pip, python3-setuptools ]
    state: present
  tags: kubernetes-hetzner

- name: Upgrade pip3
  pip:
    name: pip
    extra_args: --upgrade
  tags: kubernetes-hetzner

- name: Ensure openshift is installed for k8s module
  pip:
    name: [ openshift, pyhelm, grpcio ]
    state: present
  tags: kubernetes-hetzner

- name: Ensure additonal systemd directories
  file:
    path: "/etc/systemd/system/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - kubelet.service.d
    - docker.service.d
  tags: kubernetes-hetzner

- name: Configure kubelet for Hetzner Cloud Controller Manager
  template:
    src: kubelet.service.d/20-hetzner-cloud.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/20-hetzner-cloud.conf
    owner: root
    group: root
    mode: 0644
  notify: Reread Systemd Configuration
  tags: kubernetes-hetzner

- name: Configure docker to use systemd cgroups
  template:
    src: docker.service.d/00-cgroup-systemd.conf.j2
    dest: /etc/systemd/system/docker.service.d/00-cgroup-systemd.conf
    owner: root
    group: root
    mode: 0644
  notify: Reread Systemd Configuration
  tags: kubernetes-hetzner

- name: Set sysctl settings for traffic forwarding between nodes
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  tags: kubernetes-hetzner
